import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./../styles/globals.css";
import "./../styles/normalize.css";
import { QueryProvider } from "./query-provider";
import { montseratt } from './fonts';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montseratt.variable} antialiased dark`}
      >
        <QueryProvider>{children}</QueryProvider>
      </body>
    </html>
  );
}
